# Generated by Django 5.0 on 2023-12-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_rename_employees_crew_crew_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.TextField(choices=[('Pilot', 'Pilot'), ('FlightAttendant', 'Flight Attendant'), ('Mechanic', 'Mechanic'), ('GroundCrew', 'Ground Crew'), ('Concessions', 'Concessions'), ('Janitor', 'Janitor'), ('Security', 'Security'), ('Admin', 'Admin')], default='Admin', unique=True),
        ),
    ]
