# Generated by Django 5.0 on 2024-01-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_alter_department_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='plane_type',
            field=models.TextField(choices=[('Cargo', 'Cargo'), ('Passenger', 'Passenger'), ('Private', 'Private')], default='Passenger'),
        ),
    ]
