# Generated by Django 5.0 on 2024-01-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0008_plane_plane_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='plane_status',
            field=models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned'), ('Repair', 'Repair')], default='Active'),
        ),
    ]
